In [1]:
 # Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key

In [2]:
csvfile = '../weatherPy/weather_data_cities.csv'
weather_df = pd.read_csv(csvfile)
weather_df.head()

,City,Latitude,Longitude,Max Temperature (F),Humidity,Cloudiness,Wind Speed,County,Date
0,Maragogi,-9.0122,-35.2225,25.56,84,46,4.00,BR,1652560648
1,Poronaysk,49.2167,143.1167,2.99,82,100,7.77,RU,1652560649
2,Yar-Sale,66.8333,70.8333,1.84,100,100,4.28,RU,1652560649
3,Loa Janan,-0.5830,117.0950,23.56,99,100,0.69,ID,1652560650
4,Yellowknife,62.4560,-114.3525,15.31,26,75,6.71,CA,1652560650

In [3]:
fig = gmaps.figure()

locations = weather_df[['Latitude', 'Longitude']].astype(float)
humidityvalue = weather_df['Humidity'].astype(float)

heat_layer = gmaps.heatmap_layer(locations, weights = humidityvalue, 
                                 dissipating=False, max_intensity=weather_df['Humidity'].max(), 
                                 point_radius = 2)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [4]:
narrow_df = weather_df.loc[(weather_df['Max Temperature (F)'].astype(int) < 80) | (weather_df['Max Temperature (F)'].astype(int) > 70), :]
narrower_df = narrow_df.loc[(narrow_df['Wind Speed'] < 10), :]
hotel_df = narrower_df.loc[(narrower_df['Cloudiness'] == 0), :].astype(object)
hotel_df['Hotel Name'] = ''
hotel_df.head()
#len(hotel_df)

,City,Latitude,Longitude,Max Temperature (F),Humidity,Cloudiness,Wind Speed,County,Date,Hotel Name
16,Arraial do Cabo,-22.9661,-42.0278,22.98,73,0,3.6,BR,1652560655,
20,Rikitea,-23.1203,-134.9692,24.54,70,0,9.59,PF,1652560656,
21,Daurāla,29.1167,77.6833,31.87,9,0,2.62,IN,1652560657,
57,Mitchell,43.7094,-98.0298,21.73,26,0,5.14,US,1652560668,
58,Saint George,37.1041,-113.5841,33.77,8,0,2.06,US,1652560412,

In [5]:
lat = []
lng = []

for i in range(len(hotel_df)):
    lat.append(hotel_df.iloc[i, 1])
    lng.append(hotel_df.iloc[i, 2])
    

print(lat)
print(lng)
urls = []

#url = url = f"https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-33.8670522%2C151.1957362&radius=1500&type=restaurant&keyword=cruise&key=YOUR_API_KEY"

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

for i in range(len(lat)):
    urls.append(f'{base_url}?location={lat[i]}%2C{lng[i]}')

print(urls)

parameters = { 
            'type' : 'lodging',
            'radius': 5000,
            'key' : g_key
}
hotel_names = []

for url in urls:
    response = requests.get(url, parameters)
    data = response.json()
    hotel_names.append(data['results'][0]['name'])

[-22.9661, -23.1203, 29.1167, 43.7094, 37.1041, -16.8392, -16.5167, 33.2001, -15.1961, 37.5683, -11.3847, 19.7297, -16.4833, 60.0973, 40.5982, 34.1667, -32.5, -24.8667, 28.0206, -41.8697, -38.0023, 34.4133, 34.6391, 53.1667, -33.9258, 36.4337, 45.2986, 21.3906, -33.0117, -32.9468, 29.1614, 22.2394, 34.4839, -20.2833, -21.3393, 49.0, 53.5237, -28.55, 25.2919, -34.0527, -35.1167, 45.0205, -22.45, 18.2164, 22.9333, 28.3062, -4.5772, -23.7167, -13.2, 40.973, -15.3292, 29.0331, 26.0023, 22.5667, -45.5752, 25.0213, -23.865, -13.3128, 20.9, 38.421, 64.5011, 12.0333, 33.5862, -41.1456, 40.626, 40.5219, 30.2947, 27.0377, 49.9811, 33.9831, -10.8764, 17.0151, 33.5959, 34.8014, 20.8667, 25.9167, -20.7377, 43.3108, -45.8667, 24.7475, 40.6669, -23.4, 21.4267, -9.6608]
[-42.0278, -134.9692, 77.6833, -98.0298, -113.5841, 36.9856, -151.75, -97.1336, 12.1522, 126.9778, 43.2844, -155.09, -151.75, 19.9348, -124.1573, 77.5833, 137.7667, 113.6333, -97.0544, -73.8203, -57.5575, -119.861, -120.4579, 63.5833, 18.4232, -99.3904, 35.7771, -158.1547, 17.9442, -60.6393, 16.139, 68.9678, -114.3224, 44.2833, 55.4781, 1.9167, -2.4935, 16.4333, 60.643, 23.3716, 139.2667, -93.218, 18.9667, 42.5053, 57.5333, 70.1307, -81.2719, 44.3833, 49.05, -117.7357, 28.682, 21.5482, 63.044, 59.5289, -72.0662, 37.2685, 35.3833, 35.2406, 70.3667, -121.4238, -165.4064, 39.0333, -86.2861, -71.3082, 14.3744, -111.9391, -81.3931, 14.4283, 92.0667, 51.4364, 26.5969, 54.0924, 56.9244, -106.5436, -90.4, 73.6667, 116.8463, 3.4758, -67.5, 67.9235, -111.888, 21.7167, 39.8261, 20.3916]
['https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-22.9661%2C-42.0278', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-23.1203%2C-134.9692', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=29.1167%2C77.6833', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=43.7094%2C-98.0298', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=37.1041%2C-113.5841', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-16.8392%2C36.9856', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-16.5167%2C-151.75', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=33.2001%2C-97.1336', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-15.1961%2C12.1522', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=37.5683%2C126.9778', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-11.3847%2C43.2844', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=19.7297%2C-155.09', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-16.4833%2C-151.75', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=60.0973%2C19.9348', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=40.5982%2C-124.1573', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=34.1667%2C77.5833', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-32.5%2C137.7667', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-24.8667%2C113.6333', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=28.0206%2C-97.0544', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-41.8697%2C-73.8203', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-38.0023%2C-57.5575', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=34.4133%2C-119.861', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=34.6391%2C-120.4579', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=53.1667%2C63.5833', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-33.9258%2C18.4232', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=36.4337%2C-99.3904', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=45.2986%2C35.7771', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=21.3906%2C-158.1547', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-33.0117%2C17.9442', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-32.9468%2C-60.6393', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=29.1614%2C16.139', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=22.2394%2C68.9678', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=34.4839%2C-114.3224', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-20.2833%2C44.2833', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-21.3393%2C55.4781', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=49.0%2C1.9167', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=53.5237%2C-2.4935', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-28.55%2C16.4333', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=25.2919%2C60.643', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-34.0527%2C23.3716', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-35.1167%2C139.2667', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=45.0205%2C-93.218', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-22.45%2C18.9667', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=18.2164%2C42.5053', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=22.9333%2C57.5333', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=28.3062%2C70.1307', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-4.5772%2C-81.2719', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-23.7167%2C44.3833', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-13.2%2C49.05', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=40.973%2C-117.7357', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-15.3292%2C28.682', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=29.0331%2C21.5482', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=26.0023%2C63.044', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=22.5667%2C59.5289', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-45.5752%2C-72.0662', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=25.0213%2C37.2685', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-23.865%2C35.3833', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-13.3128%2C35.2406', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=20.9%2C70.3667', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=38.421%2C-121.4238', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=64.5011%2C-165.4064', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=12.0333%2C39.0333', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=33.5862%2C-86.2861', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-41.1456%2C-71.3082', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=40.626%2C14.3744', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=40.5219%2C-111.9391', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=30.2947%2C-81.3931', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=27.0377%2C14.4283', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=49.9811%2C92.0667', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=33.9831%2C51.4364', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-10.8764%2C26.5969', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=17.0151%2C54.0924', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=33.5959%2C56.9244', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=34.8014%2C-106.5436', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=20.8667%2C-90.4', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=25.9167%2C73.6667', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-20.7377%2C116.8463', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=43.3108%2C3.4758', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-45.8667%2C-67.5', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=24.7475%2C67.9235', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=40.6669%2C-111.888', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-23.4%2C21.7167', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=21.4267%2C39.8261', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-9.6608%2C20.3916']

IndexError: list index out of range

In [6]:
hotel_df = hotel_df.iloc[:-1 , :]
hotel_df = hotel_df.iloc[:-1 , :]
hotel_df = hotel_df.iloc[:-1 , :]

hotel_df['Hotel Name'] = hotel_names
hotel_df.head()

,City,Latitude,Longitude,Max Temperature (F),Humidity,Cloudiness,Wind Speed,County,Date,Hotel Name
16,Arraial do Cabo,-22.9661,-42.0278,22.98,73,0,3.6,BR,1652560655,Pousada Porto Praia
20,Rikitea,-23.1203,-134.9692,24.54,70,0,9.59,PF,1652560656,People ThankYou
21,Daurāla,29.1167,77.6833,31.87,9,0,2.62,IN,1652560657,SAGAR KATARIYA
57,Mitchell,43.7094,-98.0298,21.73,26,0,5.14,US,1652560668,Kelly Inn & Suites
58,Saint George,37.1041,-113.5841,33.77,8,0,2.06,US,1652560412,Best Western Plus Abbey Inn

In [7]:
# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{County}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]
markers = gmaps.marker_layer(locations, 
                            info_box_content = [f'{hotel}' for hotel in hotel_info])

fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))